package fits

import (
	"math"
	"path/filepath"
	"testing"
)

// TestCompressedFixtures is the main integration test for tile
// compression. For each (compressed, raw) fixture pair generated by
// testdata/generate_compressed.py, it verifies that reading the
// compressed file and decompressing tiles produces pixel values
// matching the raw-uncompressed counterpart.
//
// Lossless algorithms (RICE_1 on integer data, GZIP_1/GZIP_2 on integer,
// NOCOMPRESS, PLIO_1) require exact equality. Lossy algorithms (RICE_1
// with quantize_level on float data, HCOMPRESS_1 lossy mode) require
// match to within the quantization precision.
func TestCompressedFixtures(t *testing.T) {
	cases := []struct {
		name       string
		comp       string
		raw        string
		algo       string
		exact      bool    // require exact pixel equality
		tolerance  float64 // absolute tolerance for float comparisons (lossy)
		pixelType  string  // "int16", "int32", "float32"
	}{
		{"RICE_1 int16", "comp_rice_i16.fits", "comp_raw_rice_i16.fits", "RICE_1", true, 0, "int16"},
		{"RICE_1 int32", "comp_rice_i32.fits", "comp_raw_rice_i32.fits", "RICE_1", true, 0, "int32"},
		{"GZIP_1 int16", "comp_gzip1_i16.fits", "comp_raw_gzip1_i16.fits", "GZIP_1", true, 0, "int16"},
		{"GZIP_1 int32", "comp_gzip1_i32.fits", "comp_raw_gzip1_i32.fits", "GZIP_1", true, 0, "int32"},
		{"GZIP_2 int16", "comp_gzip2_i16.fits", "comp_raw_gzip2_i16.fits", "GZIP_2", true, 0, "int16"},
		{"GZIP_2 int32", "comp_gzip2_i32.fits", "comp_raw_gzip2_i32.fits", "GZIP_2", true, 0, "int32"},
		{"NOCOMPRESS int16", "comp_nocompress_i16.fits", "comp_raw_nocompress_i16.fits", "NOCOMPRESS", true, 0, "int16"},
		{"PLIO_1 mask", "comp_plio_mask.fits", "comp_raw_plio_mask.fits", "PLIO_1", true, 0, "int16"},
		// Float RICE with quantization: lossy to ~ZSCALE precision.
		{"RICE_1 float32 nodither", "comp_rice_f32_nodither.fits", "comp_raw_rice_f32_nodither.fits", "RICE_1", false, 0.1, "float32"},
		{"RICE_1 float32 dither", "comp_rice_f32_dither.fits", "comp_raw_rice_f32_dither.fits", "RICE_1", false, 0.1, "float32"},
		{"GZIP_1 float32", "comp_gzip1_f32.fits", "comp_raw_gzip1_f32.fits", "GZIP_1", false, 0.1, "float32"},
		{"GZIP_2 float32", "comp_gzip2_f32.fits", "comp_raw_gzip2_f32.fits", "GZIP_2", false, 0.1, "float32"},
		// Tile geometry edge cases.
		{"RICE_1 multi-tile", "comp_rice_multitile.fits", "comp_raw_rice_multitile.fits", "RICE_1", true, 0, "int16"},
		{"RICE_1 one-tile", "comp_rice_onetile.fits", "comp_raw_rice_onetile.fits", "RICE_1", true, 0, "int16"},
		{"RICE_1 odd shape", "comp_rice_odd.fits", "comp_raw_rice_odd.fits", "RICE_1", true, 0, "int16"},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			compPath := filepath.Join("testdata", c.comp)
			rawPath := filepath.Join("testdata", c.raw)

			comp, err := Open(compPath)
			if err != nil {
				t.Fatalf("open compressed: %v", err)
			}
			defer comp.Close()

			// HDU 1 is the compressed image.
			cHDU, err := comp.HDU(1)
			if err != nil {
				t.Fatalf("HDU(1): %v", err)
			}
			cimg, ok := cHDU.(*CompressedImageHDU)
			if !ok {
				t.Fatalf("HDU(1) is %T, expected *CompressedImageHDU", cHDU)
			}
			if got := cimg.CompressionType(); got != c.algo {
				t.Errorf("CompressionType = %q, want %q", got, c.algo)
			}

			raw, err := Open(rawPath)
			if err != nil {
				t.Fatalf("open raw: %v", err)
			}
			defer raw.Close()
			rHDU, err := raw.HDU(1)
			if err != nil {
				t.Fatalf("HDU(1) raw: %v", err)
			}
			rimg := rHDU.(*ImageHDU)

			// Verify shapes match.
			if cimg.BITPIX() != rimg.BITPIX() {
				t.Fatalf("BITPIX mismatch: comp=%d raw=%d", cimg.BITPIX(), rimg.BITPIX())
			}
			cs := cimg.Shape()
			rs := rimg.Shape()
			if len(cs) != len(rs) {
				t.Fatalf("NAXIS mismatch: comp=%d raw=%d", len(cs), len(rs))
			}
			for i := range cs {
				if cs[i] != rs[i] {
					t.Fatalf("NAXIS%d mismatch: comp=%d raw=%d", i+1, cs[i], rs[i])
				}
			}

			// Read both and compare per type.
			switch c.pixelType {
			case "int16":
				gotPix, err := ReadPixelsCompressed[int16](cimg)
				if err != nil {
					t.Fatalf("decompress: %v", err)
				}
				wantPix, _ := ReadPixels[int16](rimg)
				comparePixelsInt16(t, gotPix, wantPix, c.exact)
			case "int32":
				gotPix, err := ReadPixelsCompressed[int32](cimg)
				if err != nil {
					t.Fatalf("decompress: %v", err)
				}
				wantPix, _ := ReadPixels[int32](rimg)
				comparePixelsInt32(t, gotPix, wantPix, c.exact)
			case "float32":
				gotPix, err := ReadPixelsCompressed[float32](cimg)
				if err != nil {
					t.Fatalf("decompress: %v", err)
				}
				wantPix, _ := ReadPixels[float32](rimg)
				comparePixelsFloat32(t, gotPix, wantPix, c.tolerance)
			}
		})
	}
}

func comparePixelsInt16(t *testing.T, got, want []int16, exact bool) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("length mismatch: got %d want %d", len(got), len(want))
	}
	diffs := 0
	firstDiff := -1
	for i := range got {
		if got[i] != want[i] {
			if firstDiff < 0 {
				firstDiff = i
			}
			diffs++
		}
	}
	if exact && diffs > 0 {
		t.Errorf("%d pixel mismatches (of %d); first at idx %d: got %d want %d",
			diffs, len(got), firstDiff, got[firstDiff], want[firstDiff])
	}
}

func comparePixelsInt32(t *testing.T, got, want []int32, exact bool) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("length mismatch: got %d want %d", len(got), len(want))
	}
	diffs := 0
	firstDiff := -1
	for i := range got {
		if got[i] != want[i] {
			if firstDiff < 0 {
				firstDiff = i
			}
			diffs++
		}
	}
	if exact && diffs > 0 {
		t.Errorf("%d pixel mismatches (of %d); first at idx %d: got %d want %d",
			diffs, len(got), firstDiff, got[firstDiff], want[firstDiff])
	}
}

func comparePixelsFloat32(t *testing.T, got, want []float32, tolerance float64) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("length mismatch: got %d want %d", len(got), len(want))
	}
	maxDiff := 0.0
	badIdx := -1
	for i := range got {
		if math.IsNaN(float64(got[i])) && math.IsNaN(float64(want[i])) {
			continue
		}
		d := math.Abs(float64(got[i] - want[i]))
		if d > maxDiff {
			maxDiff = d
			badIdx = i
		}
	}
	if maxDiff > tolerance {
		t.Errorf("max float diff %g > tolerance %g; at idx %d got %v want %v",
			maxDiff, tolerance, badIdx, got[badIdx], want[badIdx])
	}
}
